version: '3.8'

networks:
  loyalty-network:
    driver: overlay
  traefik-public:
    external: true

services:
  loyalty-app:
    image: loyalty-app
    build:
      context: https://github.com/danipiovesan/loyalty-new.git#main
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        # Router principal
        - "traefik.http.routers.loyalty.rule=Host(`fidelidade.pioxiiodontologia.com.br`)"
        - "traefik.http.routers.loyalty.entrypoints=websecure"
        - "traefik.http.routers.loyalty.tls=true"
        - "traefik.http.routers.loyalty.service=loyalty-service"
        # Service
        - "traefik.http.services.loyalty-service.loadbalancer.server.port=8080"
        # Middleware para CORS e headers
        - "traefik.http.middlewares.loyalty-headers.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS"
        - "traefik.http.middlewares.loyalty-headers.headers.accesscontrolalloworiginlist=*"
        - "traefik.http.middlewares.loyalty-headers.headers.accesscontrolmaxage=100"
        - "traefik.http.middlewares.loyalty-headers.headers.addvaryheader=true"
        # Aplicar middleware
        - "traefik.http.routers.loyalty.middlewares=loyalty-headers"
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - NODE_ENV=production
      - DATABASE_URL=sqlite:///app/data/loyalty.db
      - PORT=8080
      - HOST=0.0.0.0
    volumes:
      - loyalty-data:/app/data
    networks:
      - loyalty-network
      - traefik-public

  loyalty-db-init:
    image: loyalty-app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    command: node src/lib/db/init.js
    volumes:
      - loyalty-data:/app/data
    environment:
      - DATABASE_URL=sqlite:///app/data/loyalty.db
    networks:
      - loyalty-network

volumes:
  loyalty-data:
    driver: local
