version: '3.8'

services:
  loyalty-app:
    image: loyalty-app:latest
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=sqlite:///app/data/loyalty.db
      - PORT=8080
      - HOST=0.0.0.0
    volumes:
      - loyalty-data:/app/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  loyalty-db-init:
    image: loyalty-app:latest
    command: node src/lib/db/init.js
    volumes:
      - loyalty-data:/app/data
    environment:
      - DATABASE_URL=sqlite:///app/data/loyalty.db
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  loyalty-data:
    driver: local
